# Generated by Django 3.0.2 on 2020-01-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_campanha', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='imagens/')),
            ],
        ),
    ]
