# Generated by Django 3.0.2 on 2020-01-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0004_auto_20200130_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='pub_date',
        ),
    ]
